from fedora:24

run dnf install -y wget && cd /tmp && wget http://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-6.3.7-2.fc24.x86_64.rpm && dnf install -y mysql-workbench-community-6.3.7-2.fc24.x86_64.rpm

entrypoint mysql-workbench

